### ISSUE TITLE
Würzburg (Landkreis) looking strange

### ISSUE THREAD

**Issue by ghost** [mojoaxel/corona-data-germany#4]
- Dead people resurrecting
- Older case numbers very different to RKI data

https://niklas-deutschmann.de/covid19#/09679

**Comment by mojoaxel** [comment]
The numbers for the infected cases look good (our data start at 20.03.20):
![image](https://user-images.githubusercontent.com/600565/77860036-20e15100-720d-11ea-9c74-c3c01ec1ec60.png)
![image](https://user-images.githubusercontent.com/600565/77860045-39516b80-720d-11ea-92b5-e448b9299381.png)

There but the `death_total` makes no sense! I'll have a look!

**Comment by mojoaxel** [comment]
I see two possibilities how this could have happend:
- I had a bug in my collector.
- The RKI had false data and repaired it.

I'm working on a fix.

**Comment by mojoaxel** [comment]
It looks like the RKI fixed its data. 
I fixed this by updating our historical data:

![image](https://user-images.githubusercontent.com/600565/77861970-b1715e80-7218-11ea-8d11-9de40a962f66.png)
